### Register User
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "nama": "John Doe3",
    "email": "johndoe3@example.com",
    "password": "password123",
    "confirmPassword": "password123",
    "gender": "male",
    "tanggalLahir": "1990-01-01"
}
### Login User
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email": "johndoe3@example.com",
    "password": "password123"
}

### get all user
GET http://localhost:3000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc
#### token
GET http://localhost:3000/api/v1/token

### Logout
DELETE http://localhost:3000/api/v1/logout

### Save Cart
POST  http://localhost:3000/api/v1/checkout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc
Content-Type: application/json

{
    "quantity":3,
    "product_id": 2
}

### get all Cart
GET http://localhost:3000/api/v1/checkout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc


### update quantity
PUT http://localhost:3000/api/v1/checkout/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc
Content-Type: application/json

{
    "itemId": 1,
    "qty": 3
}

### delete all item
DELETE  http://localhost:3000/api/v1/checkout/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc
Content-Type: application/json

{
    "cart_id": 1
}

### delete item by id
DELETE  http://localhost:3000/api/v1/checkout/delete/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc
Content-Type: application/json

{
    "itemId": 7
}



### Get All Orders
GET http://localhost:3000/api/v1/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc

### Get Order By ID
GET http://localhost:3000/api/v1/order/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc

### Make Shipping Address
POST http://localhost:3000/api/v1/shipping
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc

{
  "address": "123 Street",
  "city": "City",
  "country": "Country",
  "postal": "12345",
  "courier": "Courier",
  "cost": 50000
}

### Make Order
POST http://localhost:3000/api/v1/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc
Content-Type: application/json

{
  "shipping_id": 2,
  "ordersItem": [
    {
      "product_id": 1,
      "quantity": 3,
      "total_price": 600000
    }
  ]
}


### Proses Transaksi
POST http://localhost:3000/api/v1/transaction
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc

{
  "shipping_id": 2,
  "payment_type": "bca_va",
  "customer_details": {
    "first_name": "John Doe3",
    "email": "johndoe3@example.com"
  }
}

### Pembayaran Sukses
POST http://localhost:3000/api/v1/transaction/success
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc

{
  "transaction": {
    "orderId": "4414c346-3696-47d2-add7-7429a888eb2d",
    "fraud_status": "accept",
    "transaction_status": "settlement"
  }
}

### Update Order Status
PUT http://localhost:3000/api/v1/status
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc

{
  "status": "dikirim"
}



 