### Register User
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "nama": "Mamat Sentosa",
    "email": "mamat@email.com",
    "password": "ayamnaikHaji",
    "confirmPassword": "ayamnaikHaji",
    "gender": "male",
    "tanggalLahir": "1994-06-10"
}
### Login User
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email": "farhan@gmail.com",
    "password": "123"
}

### update User
PUT  http://localhost:3000/api/v1/editUser/0178d6b5-e1f3-46c0-859c-83625972a7b5
Authorization:Bearer 
Content-Type: application/json
{
  "nama": "orang ganteng"
}
### get all user
GET http://localhost:3000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc
#### token
GET http://localhost:3000/api/v1/token

### Logout
DELETE http://localhost:3000/api/v1/logout

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxNzhkNmI1LWUxZjMtNDZjMC04NTljLTgzNjI1OTcyYTdiNSIsIm5hbWUiOiJUcmV2b3IgUm9kcmlndWV6IiwiZW1haWwiOiJCcmVuZGEuQ29ubmVsbHlAZ21haWwuY29tIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91Lzk3Mjc2NTY1IiwidGFuZ2dhbExhaGlyIjoiMjAyNC0xMC0xOFQwNTo1NjowMy4wOTdaIiwiaWF0IjoxNzMzNjcwNzM0LCJleHAiOjE3MzQ5NjY3MzR9.TZXLjmzUT3DogboPeBxlmLkriLWBuHfu5hl2xO4Zv2o
### Mengambil daftar produk favorit user
GET http://localhost:3000/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyYWIyNTIzLTFlNjMtNGUyZS1iNDliLTY2MzlhYWYyZTQxNiIsIm5hbWUiOiJndXMgcmluZGFuZyIsImVtYWlsIjoicmluZGFuZ0BnbWFpbC5jb20iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kc3puanpncWgvaW1hZ2UvdXBsb2FkL3YxNzMzNzU1Mzc4L2pqMXJjeHlvYmVibW9tcGpvZW1jLnBuZyIsInRhbmdnYWxMYWhpciI6IjIwMjQtMTItMDlUMTc6MDA6MDAuMDAwWiIsImlhdCI6MTczMzg0MzQ0NSwiZXhwIjoxNzM1MTM5NDQ1fQ.k4IUt22AS47YOH3rItQg2LIolN5PEws3HjCmOlSDBd8
###

### Menambahkan produk ke daftar favorit
POST http://localhost:3000/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyYWIyNTIzLTFlNjMtNGUyZS1iNDliLTY2MzlhYWYyZTQxNiIsIm5hbWUiOiJndXMgcmluZGFuZyIsImVtYWlsIjoicmluZGFuZ0BnbWFpbC5jb20iLCJwcm9maWxlSW1hZ2UiOiJodHRwczovL3Jlcy5jbG91ZGluYXJ5LmNvbS9kc3puanpncWgvaW1hZ2UvdXBsb2FkL3YxNzMzNzU1Mzc4L2pqMXJjeHlvYmVibW9tcGpvZW1jLnBuZyIsInRhbmdnYWxMYWhpciI6IjIwMjQtMTItMDlUMTc6MDA6MDAuMDAwWiIsImlhdCI6MTczMzg0MzQ0NSwiZXhwIjoxNzM1MTM5NDQ1fQ.k4IUt22AS47YOH3rItQg2LIolN5PEws3HjCmOlSDBd8
Content-Type: application/json

{
  "productId": 10
}

###

### Menghapus produk dari daftar favorit
DELETE http://localhost:3000/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3OTdlZTQwZi02Njk5LTQzYWUtODc3ZC1kYTYzMTRkMGVkMzEiLCJuYW1lIjoiTWFtYXQgU2VudG9zYSIsImVtYWlsVXNlciI6Im1hbWF0QGVtYWlsLmNvbSIsImlhdCI6MTczMjkzMzI2NCwiZXhwIjoxNzM0MjI5MjY0fQ.Siq-WeNEj9CiNVtQL7J8NMwTlplw52Z3sg5-eo_LQIM
Content-Type: application/json

{
  "productId": 20
}


### Save Cart
POST  http://localhost:3000/api/v1/checkout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc
Content-Type: application/json

{
    "quantity":2,
    "product_id": 1,
    "size": "XL"
}

### get all Cart
GET http://localhost:3000/api/v1/checkout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc


### update quantity
PUT http://localhost:3000/api/v1/checkout/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc
Content-Type: application/json

{
    "itemId": 1,
    "qty": 2
}

### delete all item
DELETE  http://localhost:3000/api/v1/checkout/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc
Content-Type: application/json

{
    "cart_id": 1
}

### delete item by id
DELETE  http://localhost:3000/api/v1/checkout/delete/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc
Content-Type: application/json

{
    "itemId": 2
}



### Get All Orders
GET http://localhost:3000/api/v1/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc

### Get Order By ID
GET http://localhost:3000/api/v1/order/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc

### Make Shipping Address
POST http://localhost:3000/api/v1/shipping
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc

{
  "address": "123 Street",
  "city": "City",
  "country": "Country",
  "postal": "12345",
  "courier": "Courier",
  "cost": 15000
}


### Proses Transaksi
POST http://localhost:3000/api/v1/transaction
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc

{
  "shipping_id": 1,
  "payment_type": "bni_va",
  "customer_details": {
    "first_name": "Mamat Sentosa",
    "email": "mamat@email.com"
  }
}

### Pembayaran Sukses
POST http://localhost:3000/api/v1/transaction/success
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc

{
  "transaction": {
    "orderId": "a99caa21-4e0e-4dfd-afd8-d968ea19c569",
    "fraud_status": "accept",
    "transaction_status": "settlement"
  }
}

### Update Order Status
PUT http://localhost:3000/api/v1/status
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.kIH44fgzgkKi5TXKBKB5Z3OL0C9AS22ONjIIhsLsmYc

{
  "status": "sent"
}



 